# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 22:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weatherSentiment', '0002_tweet_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 20, 22, 45, 27, 259905, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
