# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherSentiment', '0003_weather_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='precipitation',
            field=models.FloatField(),
        ),
    ]
