# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherSentiment', '0004_auto_20160220_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='zip',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
