# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherSentiment', '0005_auto_20160220_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='feels_like',
            field=models.CharField(default='Good', max_length=200),
            preserve_default=False,
        ),
    ]
